source('text_processing_functions.R')
source('vis_calculation_functions.R')
test = tokenize('nyt-collection-text/art/0068412.txt')
unique_test = filter_unique(test)
unique_test = filter_stopwords(unique_test, 'stopwords_xpo6.csv')
weights = weight_by_counts(unique_test, test)
weights = filter_rare(weights, nmin=3)
weights = sort_by_weight(weights)
bounding_boxes = bounding_box(colnames(weights), hscale = weights/min(weights), vscale = weights/min(weights))
coordinates = place_words(weights, bounding_boxes)
add_bounding_boxes(coordinates, bounding_boxes)

plot.new()
plot.window(xlim = c(-1, 1), ylim = c(-1, 1))
points(x=0, y=0)
text(0,0,"test",adj=c(0,0))
text(0,0,"test01",adj=c(0,1))
text(0,0,"test10",adj=c(1,0))
text(0,0,"test11",adj=c(1,1))
points(c(0,0))
