
Created from within nyt-collection by

foreach file (art/*.xml)
  python textify.py $file ../nyt-collection-text/art/$file:t:r.txt
  echo $file
end

foreach file (music/*.xml)
  python textify.py $file ../nyt-collection-text/music/$file:t:r.txt
  echo $file
end

using the textify.py script in Src.

